"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.cybJobExperiences = exports.cybJobCollaboratorLogs = exports.cybJobCollaborators = exports.cybInstitutions = exports.cybIndustries = exports.cybHelp = exports.cybGender = exports.cybGalleries = exports.cybFrontMenu = exports.cybFollow = exports.cybFaqs = exports.cybEventMenu = exports.cybEnquiries = exports.cybEmployementType = exports.cybEmailTemplates = exports.cybEmailBlacklist = exports.cybDoctype = exports.cybDesignation = exports.cybDepartment = exports.cybDeleteOptions = exports.cybCustomerVisits = exports.cybCrmCall = exports.cybCourseType = exports.cybCourses = exports.cybCountry = exports.cybCompanyWishlist = exports.cybCompanySize = exports.cybCompanyJob = exports.cybCompanyInvite = exports.cybCompanyDocument = exports.cybCompanyConnection = exports.cybCompanyBranches = exports.cybCompanyBenefits = exports.cybClarity = exports.cybClaimCompanyEnquires = exports.cybCities = exports.cybChatSupport = exports.cybCategories = exports.cybCareerEnquiries = exports.cybBranches = exports.cybBlog = exports.cybBenefits = exports.cybAuthor = exports.cybApplication = exports.cybAdminPermission = exports.cybAdminGroup = exports.cybAdmin = exports.cybAccountSetting = exports.cybAccountDeleteRequests = exports.cybAccomodation = void 0;
exports.cybUserEducation = exports.cybUserDomains = exports.cybUserDocument = exports.cybUserDeviceTokens = exports.cybUserDetails = exports.cybUserContacts = exports.cybUserCertificate = exports.cybUser = exports.cybTurnover = exports.cybTriggerEmail = exports.cybTrackEmails = exports.cybTag = exports.cybSuggestion = exports.cybState = exports.cybSkillRatingHistory = exports.cybSkillRating = exports.cybSkill = exports.cybSetting = exports.cybSchedularHistory = exports.cybSchedularEmailTemp = exports.cybSchedulars = exports.cybSalary = exports.cybRoleTypes = exports.cybResumeTemplates = exports.cybResumeDownload = exports.cybRestaurantCustomers = exports.cybRestaurantCategory = exports.cybRestaurants = exports.cybReportReviews = exports.cybReels = exports.cybRatingWeight = exports.cybRamdomWidgets = exports.cybPortfolioDocumentType = exports.cybPermission = exports.cybOtp = exports.cybNotifications = exports.cybNoticePeriod = exports.cybMonth = exports.cybMigrations = exports.cybMessageHistory = exports.cybMessage = exports.cybMergeCompanyRequest = exports.cybMergeCompany = exports.cybMenu = exports.cybManualDocumentVerify = exports.cybLogs = exports.cybLanguages = exports.cybJobTemplate = exports.cybJobMode = exports.cybJobMeta = void 0;
exports.cybWorkType = exports.cybWidgetPosition = exports.cybWidgets = exports.cybWebMenu = exports.cybViewImpressions = exports.cybVerifyDocument = exports.cybUserUpdateExperienceHistory = exports.cybUserUpdateExperience = exports.cybUserSkill = exports.cybUserRelation = exports.cybUserProtfolio = exports.cybUserProfileViewRequest = exports.cybUserPermission = exports.cybUserMainGroup = exports.cybUserLoginHistory = exports.cybUserLevels = exports.cybUserLanguage = exports.cybUserGroup = exports.cybUserExperienceRatingHistory = exports.cybUserExperienceRating = exports.cybUserExperience = void 0;
const mysql_core_1 = require("drizzle-orm/mysql-core");
const drizzle_orm_1 = require("drizzle-orm");
exports.cybAccomodation = (0, mysql_core_1.mysqlTable)("cyb_accomodation", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    status: (0, mysql_core_1.int)(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 100 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 100 }),
});
exports.cybAccountDeleteRequests = (0, mysql_core_1.mysqlTable)("cyb_account_delete_requests", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id").notNull(),
    optionId: (0, mysql_core_1.int)("option_id").notNull(),
    message: (0, mysql_core_1.text)(),
    expiry: (0, mysql_core_1.varchar)({ length: 250 }),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    status: (0, mysql_core_1.int)().default(1),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
});
exports.cybAccountSetting = (0, mysql_core_1.mysqlTable)("cyb_account_setting", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id").notNull(),
    code: (0, mysql_core_1.varchar)({ length: 250 }),
    key: (0, mysql_core_1.varchar)({ length: 250 }),
    value: (0, mysql_core_1.varchar)({ length: 250 }),
    status: (0, mysql_core_1.int)().default(1).notNull(),
}, (table) => [
    (0, mysql_core_1.index)("idx_user_id").on(table.userId),
]);
exports.cybAdmin = (0, mysql_core_1.mysqlTable)("cyb_admin", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    username: (0, mysql_core_1.varchar)({ length: 100 }).notNull(),
    permission: (0, mysql_core_1.longtext)(),
    firstname: (0, mysql_core_1.varchar)({ length: 250 }),
    lastname: (0, mysql_core_1.varchar)({ length: 100 }),
    email: (0, mysql_core_1.varchar)({ length: 250 }),
    individualId: (0, mysql_core_1.varchar)("individual_id", { length: 50 }),
    password: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    userGroupId: (0, mysql_core_1.int)("user_group_id"),
    photo: (0, mysql_core_1.varchar)({ length: 250 }),
    isSuper: (0, mysql_core_1.int)("is_super").default(0).notNull(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    lastLogin: (0, mysql_core_1.varchar)("last_login", { length: 250 }),
    createdBy: (0, mysql_core_1.int)("created_by"),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }).notNull(),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }).notNull(),
});
exports.cybAdminGroup = (0, mysql_core_1.mysqlTable)("cyb_admin_group", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    permission: (0, mysql_core_1.text)(),
    rights: (0, mysql_core_1.text)(),
    widgets: (0, mysql_core_1.text)(),
    masking: (0, mysql_core_1.int)(),
    isSuper: (0, mysql_core_1.int)("is_super").default(0).notNull(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createdBy: (0, mysql_core_1.int)("created_by"),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 100 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 100 }),
});
exports.cybAdminPermission = (0, mysql_core_1.mysqlTable)("cyb_admin_permission", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userGroup: (0, mysql_core_1.int)("user_group"),
    menu: (0, mysql_core_1.int)(),
    permission: (0, mysql_core_1.longtext)(),
});
exports.cybApplication = (0, mysql_core_1.mysqlTable)("cyb_application", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    job: (0, mysql_core_1.int)(),
    user: (0, mysql_core_1.int)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }).notNull(),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybAuthor = (0, mysql_core_1.mysqlTable)("cyb_author", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 150 }).notNull(),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybBenefits = (0, mysql_core_1.mysqlTable)("cyb_benefits", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.text)(),
    image: (0, mysql_core_1.varchar)({ length: 250 }),
    description: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    userDefined: (0, mysql_core_1.int)("user_defined"),
    userId: (0, mysql_core_1.int)("user_id"),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybBlog = (0, mysql_core_1.mysqlTable)("cyb_blog", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    title: (0, mysql_core_1.text)(),
    image: (0, mysql_core_1.text)(),
    thumbnailImage: (0, mysql_core_1.text)("thumbnail_image"),
    description: (0, mysql_core_1.text)(),
    shortDescription: (0, mysql_core_1.text)("short_description"),
    // you can use { mode: 'date' }, if you want to have Date as type for this column
    publishDate: (0, mysql_core_1.date)("publish_date", { mode: 'string' }),
    readingTime: (0, mysql_core_1.time)("reading_time"),
    authorId: (0, mysql_core_1.varchar)("author_id", { length: 100 }),
    categoryId: (0, mysql_core_1.int)("category_id").notNull(),
    slug: (0, mysql_core_1.text)(),
    sortOrder: (0, mysql_core_1.int)("sort_order"),
    metaTitle: (0, mysql_core_1.text)("meta_title"),
    metaKeyword: (0, mysql_core_1.text)("meta_keyword"),
    metaDescription: (0, mysql_core_1.text)("meta_description"),
    h1Tag: (0, mysql_core_1.varchar)("h1_tag", { length: 255 }),
    footerDescription: (0, mysql_core_1.text)("footer_description"),
    metaRobots: (0, mysql_core_1.varchar)("meta_robots", { length: 100 }),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybBranches = (0, mysql_core_1.mysqlTable)("cyb_branches", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.int)(),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }).notNull(),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }).notNull(),
});
exports.cybCareerEnquiries = (0, mysql_core_1.mysqlTable)("cyb_career_enquiries", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    firstName: (0, mysql_core_1.varchar)({ length: 100 }).notNull(),
    lastName: (0, mysql_core_1.varchar)({ length: 100 }),
    email: (0, mysql_core_1.varchar)({ length: 100 }).notNull(),
    phone: (0, mysql_core_1.varchar)({ length: 30 }).notNull(),
    message: (0, mysql_core_1.text)(),
    company: (0, mysql_core_1.varchar)({ length: 250 }),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 100 }),
});
exports.cybCategories = (0, mysql_core_1.mysqlTable)("cyb_categories", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 255 }),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybChatSupport = (0, mysql_core_1.mysqlTable)("cyb_chat_support", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    type: (0, mysql_core_1.varchar)({ length: 50 }).notNull(),
    question: (0, mysql_core_1.text)().notNull(),
    answer: (0, mysql_core_1.text)().notNull(),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybCities = (0, mysql_core_1.mysqlTable)("cyb_cities", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    state: (0, mysql_core_1.int)().default(0),
    userDifined: (0, mysql_core_1.int)("user_difined").default(0),
    userId: (0, mysql_core_1.int)("user_id").default(0),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
    status: (0, mysql_core_1.int)().default(0),
}, (table) => [
    (0, mysql_core_1.index)("cities_index").on(table.state, table.status),
]);
exports.cybClaimCompanyEnquires = (0, mysql_core_1.mysqlTable)("cyb_claim_company_enquires", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    contactPerson: (0, mysql_core_1.varchar)("contact_person", { length: 80 }).notNull(),
    company: (0, mysql_core_1.int)().notNull(),
    email: (0, mysql_core_1.varchar)({ length: 50 }),
    phone: (0, mysql_core_1.varchar)({ length: 15 }),
    website: (0, mysql_core_1.varchar)({ length: 250 }),
    message: (0, mysql_core_1.text)(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 100 }),
});
exports.cybClarity = (0, mysql_core_1.mysqlTable)("cyb_clarity", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    result: (0, mysql_core_1.longtext)(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 100 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 100 }),
});
exports.cybCompanyBenefits = (0, mysql_core_1.mysqlTable)("cyb_company_benefits", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    companyId: (0, mysql_core_1.int)("company_id").notNull(),
    benefitId: (0, mysql_core_1.int)("benefit_id").notNull(),
    description: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    sortOrder: (0, mysql_core_1.int)(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("company_benefits_index").on(table.companyId, table.benefitId, table.status, table.isDeleted),
]);
exports.cybCompanyBranches = (0, mysql_core_1.mysqlTable)("cyb_company_branches", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    branchId: (0, mysql_core_1.int)("branch_id"),
    companyId: (0, mysql_core_1.int)("company_id"),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybCompanyConnection = (0, mysql_core_1.mysqlTable)("cyb_company_connection", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    company: (0, mysql_core_1.int)(),
    user: (0, mysql_core_1.int)(),
    currentEmployee: (0, mysql_core_1.int)("current_employee").default(0),
    status: (0, mysql_core_1.int)().default(1),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybCompanyDocument = (0, mysql_core_1.mysqlTable)("cyb_company_document", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    company: (0, mysql_core_1.int)(),
    doctype: (0, mysql_core_1.varchar)({ length: 50 }),
    docName: (0, mysql_core_1.text)("doc_name"),
    docnumber: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(0).notNull(),
    verify: (0, mysql_core_1.int)().default(0),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybCompanyInvite = (0, mysql_core_1.mysqlTable)("cyb_company_invite", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    fname: (0, mysql_core_1.varchar)({ length: 250 }),
    lname: (0, mysql_core_1.varchar)({ length: 100 }),
    phone: (0, mysql_core_1.varchar)({ length: 50 }),
    email: (0, mysql_core_1.varchar)({ length: 250 }),
    profile: (0, mysql_core_1.varchar)({ length: 250 }),
    contactPerson: (0, mysql_core_1.varchar)("contact_person", { length: 250 }),
    website: (0, mysql_core_1.varchar)({ length: 250 }),
    company: (0, mysql_core_1.int)().notNull(),
    addedBy: (0, mysql_core_1.int)("added_by").notNull(),
    incorporateDate: (0, mysql_core_1.varchar)("incorporate_date", { length: 250 }),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0),
    industry: (0, mysql_core_1.int)(),
    claimStatus: (0, mysql_core_1.int)("claim_status").default(0),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 50 }),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 100 }),
});
exports.cybCompanyJob = (0, mysql_core_1.mysqlTable)("cyb_company_job", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    company: (0, mysql_core_1.int)(),
    jobTitle: (0, mysql_core_1.text)("job_title"),
    jobDescription: (0, mysql_core_1.text)("job_description"),
    slug: (0, mysql_core_1.text)(),
    rolesResponsibility: (0, mysql_core_1.text)("roles_responsibility"),
    department: (0, mysql_core_1.int)(),
    experience: (0, mysql_core_1.text)(),
    skill: (0, mysql_core_1.text)(),
    roleType: (0, mysql_core_1.int)("role_type"),
    document: (0, mysql_core_1.text)(),
    location: (0, mysql_core_1.int)(),
    country: (0, mysql_core_1.int)(),
    state: (0, mysql_core_1.int)(),
    jobMode: (0, mysql_core_1.int)("job_mode"),
    tag: (0, mysql_core_1.text)(),
    city: (0, mysql_core_1.int)(),
    industry: (0, mysql_core_1.int)(),
    designation: (0, mysql_core_1.int)(),
    urgent: (0, mysql_core_1.tinyint)(),
    vacancy: (0, mysql_core_1.int)(),
    postedDate: (0, mysql_core_1.datetime)("posted_date", { mode: 'string' }),
    closingDate: (0, mysql_core_1.datetime)("closing_date", { mode: 'string' }),
    salary: (0, mysql_core_1.int)(),
    status: (0, mysql_core_1.int)().default(1),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("jobs_index").on(table.company, table.department, table.country, table.state, table.city, table.industry, table.designation, table.vacancy, table.status, table.isDeleted, table.jobTitle, table.createDate),
]);
exports.cybCompanySize = (0, mysql_core_1.mysqlTable)("cyb_company_size", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    status: (0, mysql_core_1.int)(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybCompanyWishlist = (0, mysql_core_1.mysqlTable)("cyb_company_wishlist", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    company: (0, mysql_core_1.int)(),
    user: (0, mysql_core_1.int)(),
    status: (0, mysql_core_1.int)().default(1),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybCountry = (0, mysql_core_1.mysqlTable)("cyb_country", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 36 }),
    sortname: (0, mysql_core_1.varchar)({ length: 3 }),
    iso2: (0, mysql_core_1.varchar)({ length: 2 }),
    phonecode: (0, mysql_core_1.int)(),
    status: (0, mysql_core_1.int)(),
});
exports.cybCourses = (0, mysql_core_1.mysqlTable)("cyb_courses", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.text)().notNull(),
    image: (0, mysql_core_1.varchar)({ length: 250 }),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    userDefined: (0, mysql_core_1.int)("user_defined"),
    userId: (0, mysql_core_1.int)("user_id"),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("courses_index").on(table.status),
]);
exports.cybCourseType = (0, mysql_core_1.mysqlTable)("cyb_course_type", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybCrmCall = (0, mysql_core_1.mysqlTable)("cyb_crm_call", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    callccid: (0, mysql_core_1.varchar)({ length: 150 }).notNull(),
    userId: (0, mysql_core_1.int)("user_id"),
    callDuration: (0, mysql_core_1.varchar)("call_duration", { length: 10 }),
    callStatus: (0, mysql_core_1.int)("call_status"),
    followUpType: (0, mysql_core_1.int)("follow_up_type"),
    followUp: (0, mysql_core_1.int)("follow_up"),
    initialPercentage: (0, mysql_core_1.int)("initial_percentage"),
    // you can use { mode: 'date' }, if you want to have Date as type for this column
    nextFollowDate: (0, mysql_core_1.date)("next_follow_date", { mode: 'string' }),
    updatePercentage: (0, mysql_core_1.int)("update_percentage"),
    callOutcome: (0, mysql_core_1.int)("call_outcome"),
    remark: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybCustomerVisits = (0, mysql_core_1.mysqlTable)("cyb_customer_visits", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    restaurantId: (0, mysql_core_1.int)("restaurant_id"),
    customerId: (0, mysql_core_1.varchar)("customer_id", { length: 150 }),
    // you can use { mode: 'date' }, if you want to have Date as type for this column
    visitDate: (0, mysql_core_1.date)("visit_date", { mode: 'string' }),
    groupSize: (0, mysql_core_1.int)("group_size"),
    billBeforeAmount: (0, mysql_core_1.varchar)("bill_before_amount", { length: 10 }),
    discount: (0, mysql_core_1.varchar)({ length: 10 }),
    billAfterAmount: (0, mysql_core_1.varchar)("bill_after_amount", { length: 10 }),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.timestamp)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.timestamp)("modify_date", { mode: 'string' }),
});
exports.cybDeleteOptions = (0, mysql_core_1.mysqlTable)("cyb_delete_options", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    title: (0, mysql_core_1.varchar)({ length: 250 }),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
    status: (0, mysql_core_1.int)().default(1),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
});
exports.cybDepartment = (0, mysql_core_1.mysqlTable)("cyb_department", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.text)(),
    userDefined: (0, mysql_core_1.int)("user_defined"),
    userId: (0, mysql_core_1.int)("user_id"),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("department_index").on(table.status),
]);
exports.cybDesignation = (0, mysql_core_1.mysqlTable)("cyb_designation", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    userId: (0, mysql_core_1.int)("user_id"),
    userDefined: (0, mysql_core_1.int)("user_defined"),
    slug: (0, mysql_core_1.text)(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("department_index").on(table.status),
]);
exports.cybDoctype = (0, mysql_core_1.mysqlTable)("cyb_doctype", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    docfor: (0, mysql_core_1.int)().default(0).notNull(),
    isVerificationRequired: (0, mysql_core_1.int)("is_verification_required").default(0),
    isTextbox: (0, mysql_core_1.int)("is_textbox").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybEmailBlacklist = (0, mysql_core_1.mysqlTable)("cyb_email_blacklist", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    email: (0, mysql_core_1.varchar)({ length: 100 }).notNull(),
    reason: (0, mysql_core_1.text)(),
    source: (0, mysql_core_1.text)(),
    errorMsg: (0, mysql_core_1.text)("error_msg"),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("skill_index").on(table.email),
]);
exports.cybEmailTemplates = (0, mysql_core_1.mysqlTable)("cyb_email_templates", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    short: (0, mysql_core_1.varchar)({ length: 11 }),
    status: (0, mysql_core_1.int)(),
    type: (0, mysql_core_1.tinyint)(),
    subject: (0, mysql_core_1.text)(),
    templatePath: (0, mysql_core_1.varchar)("template_path", { length: 250 }),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybEmployementType = (0, mysql_core_1.mysqlTable)("cyb_employement_type", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybEnquiries = (0, mysql_core_1.mysqlTable)("cyb_enquiries", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    firstName: (0, mysql_core_1.varchar)({ length: 100 }).notNull(),
    lastName: (0, mysql_core_1.varchar)({ length: 100 }),
    email: (0, mysql_core_1.varchar)({ length: 100 }).notNull(),
    phone: (0, mysql_core_1.varchar)({ length: 30 }).notNull(),
    message: (0, mysql_core_1.text)(),
    company: (0, mysql_core_1.varchar)({ length: 250 }),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 100 }),
});
exports.cybEventMenu = (0, mysql_core_1.mysqlTable)("cyb_event_menu", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 150 }).notNull(),
    description: (0, mysql_core_1.varchar)({ length: 255 }),
    menuId: (0, mysql_core_1.int)("menu_id"),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybFaqs = (0, mysql_core_1.mysqlTable)("cyb_faqs", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    question: (0, mysql_core_1.varchar)({ length: 255 }),
    answer: (0, mysql_core_1.text)(),
    shortedOrder: (0, mysql_core_1.int)("shorted_order").default(1),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybFollow = (0, mysql_core_1.mysqlTable)("cyb_follow", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    followedId: (0, mysql_core_1.int)("followed_id").notNull(),
    followerId: (0, mysql_core_1.int)("follower_id").notNull(),
    status: (0, mysql_core_1.int)().default(0).notNull(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybFrontMenu = (0, mysql_core_1.mysqlTable)("cyb_front_menu", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    parentId: (0, mysql_core_1.int)("parent_id"),
    title: (0, mysql_core_1.varchar)({ length: 255 }),
    name: (0, mysql_core_1.varchar)({ length: 250 }),
    description: (0, mysql_core_1.text)(),
    image: (0, mysql_core_1.varchar)({ length: 100 }),
    position: (0, mysql_core_1.int)(),
    subTitle: (0, mysql_core_1.text)(),
    header: (0, mysql_core_1.int)(),
    footer: (0, mysql_core_1.int)(),
    link: (0, mysql_core_1.varchar)({ length: 250 }),
    sortOrder: (0, mysql_core_1.int)("sort_order"),
    metaTitle: (0, mysql_core_1.varchar)({ length: 250 }),
    metaKeyword: (0, mysql_core_1.varchar)({ length: 250 }),
    title1: (0, mysql_core_1.text)(),
    description1: (0, mysql_core_1.text)(),
    title2: (0, mysql_core_1.text)(),
    description2: (0, mysql_core_1.text)(),
    additionalImage: (0, mysql_core_1.varchar)({ length: 200 }),
    metaDescription: (0, mysql_core_1.text)(),
    sortOrderFooter: (0, mysql_core_1.int)("sort_order_footer"),
    status: (0, mysql_core_1.int)(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 100 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 100 }),
});
exports.cybGalleries = (0, mysql_core_1.mysqlTable)("cyb_galleries", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    companyId: (0, mysql_core_1.int)("company_id").notNull(),
    name: (0, mysql_core_1.text)(),
    image: (0, mysql_core_1.varchar)({ length: 250 }),
    description: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybGender = (0, mysql_core_1.mysqlTable)("cyb_gender", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 20 }).notNull(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 20 }),
});
exports.cybHelp = (0, mysql_core_1.mysqlTable)("cyb_help", {
    id: (0, mysql_core_1.int)().primaryKey().notNull(),
    experience: (0, mysql_core_1.int)(),
    subject: (0, mysql_core_1.text)(),
    message: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybIndustries = (0, mysql_core_1.mysqlTable)("cyb_industries", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    status: (0, mysql_core_1.int)().default(1),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    userId: (0, mysql_core_1.int)("user_id"),
    userDefined: (0, mysql_core_1.int)("user_defined"),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
}, (table) => [
    (0, mysql_core_1.index)("industry_index").on(table.status, table.isDeleted),
]);
exports.cybInstitutions = (0, mysql_core_1.mysqlTable)("cyb_institutions", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.text)(),
    image: (0, mysql_core_1.varchar)({ length: 250 }),
    userDefined: (0, mysql_core_1.int)("user_defined"),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    userId: (0, mysql_core_1.int)("user_id"),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybJobCollaborators = (0, mysql_core_1.mysqlTable)("cyb_job_collaborators", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    companyId: (0, mysql_core_1.int)("company_id"),
    userId: (0, mysql_core_1.text)("user_id"),
    jobId: (0, mysql_core_1.int)("job_id"),
    role: (0, mysql_core_1.mysqlEnum)(['admin', 'manager', 'recruiter', 'viewer']),
    status: (0, mysql_core_1.int)().default(1),
    invitedBy: (0, mysql_core_1.int)("invited_by"),
    createdAt: (0, mysql_core_1.datetime)("created_at", { mode: 'string' }),
    updatedAt: (0, mysql_core_1.datetime)("updated_at", { mode: 'string' }),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
}, (table) => [
    (0, mysql_core_1.unique)("uniq_company_user").on(table.companyId, table.userId, table.jobId),
]);
exports.cybJobCollaboratorLogs = (0, mysql_core_1.mysqlTable)("cyb_job_collaborator_logs", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    companyId: (0, mysql_core_1.int)("company_id"),
    userId: (0, mysql_core_1.int)("user_id"),
    module: (0, mysql_core_1.varchar)({ length: 50 }),
    action: (0, mysql_core_1.varchar)({ length: 100 }),
    createdAt: (0, mysql_core_1.datetime)("created_at", { mode: 'string' }),
});
exports.cybJobExperiences = (0, mysql_core_1.mysqlTable)("cyb_job_experiences", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    status: (0, mysql_core_1.int)(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybJobMeta = (0, mysql_core_1.mysqlTable)("cyb_job_meta", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    metaTitle: (0, mysql_core_1.varchar)("meta_title", { length: 255 }),
    metaDescription: (0, mysql_core_1.varchar)("meta_description", { length: 255 }),
    metaKeyword: (0, mysql_core_1.varchar)("meta_keyword", { length: 255 }),
    jobSlug: (0, mysql_core_1.varchar)("job_slug", { length: 255 }),
    h1Tag: (0, mysql_core_1.varchar)("h1_tag", { length: 255 }),
    footerDescription: (0, mysql_core_1.text)("footer_description"),
    metaRobot: (0, mysql_core_1.varchar)("meta_robot", { length: 100 }),
    jobId: (0, mysql_core_1.varchar)("job_id", { length: 255 }),
    countryId: (0, mysql_core_1.text)("country_id"),
    stateId: (0, mysql_core_1.text)("state_id"),
    cityId: (0, mysql_core_1.text)("city_id"),
    designationId: (0, mysql_core_1.text)("designation_id"),
    departmentId: (0, mysql_core_1.text)("department_id"),
    ogImage: (0, mysql_core_1.varchar)("og_image", { length: 255 }),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybJobMode = (0, mysql_core_1.mysqlTable)("cyb_job_mode", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    status: (0, mysql_core_1.int)().default(1),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybJobTemplate = (0, mysql_core_1.mysqlTable)("cyb_job_template", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    company: (0, mysql_core_1.int)(),
    jobTitle: (0, mysql_core_1.text)("job_title"),
    templateName: (0, mysql_core_1.varchar)("template_name", { length: 50 }),
    jobDescription: (0, mysql_core_1.text)("job_description"),
    slug: (0, mysql_core_1.text)(),
    rolesResponsibility: (0, mysql_core_1.text)("roles_responsibility"),
    department: (0, mysql_core_1.int)(),
    experience: (0, mysql_core_1.text)(),
    skill: (0, mysql_core_1.text)(),
    roleType: (0, mysql_core_1.int)("role_type"),
    document: (0, mysql_core_1.text)(),
    location: (0, mysql_core_1.int)(),
    country: (0, mysql_core_1.int)(),
    state: (0, mysql_core_1.int)(),
    jobMode: (0, mysql_core_1.int)("job_mode"),
    tag: (0, mysql_core_1.text)(),
    city: (0, mysql_core_1.int)(),
    industry: (0, mysql_core_1.int)(),
    designation: (0, mysql_core_1.int)(),
    urgent: (0, mysql_core_1.tinyint)(),
    vacancy: (0, mysql_core_1.int)(),
    postedDate: (0, mysql_core_1.datetime)("posted_date", { mode: 'string' }),
    closingDate: (0, mysql_core_1.datetime)("closing_date", { mode: 'string' }),
    salary: (0, mysql_core_1.int)(),
    status: (0, mysql_core_1.int)().default(1),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("jobs_index").on(table.company, table.department, table.country, table.state, table.city, table.industry, table.designation, table.vacancy, table.status),
]);
exports.cybLanguages = (0, mysql_core_1.mysqlTable)("cyb_languages", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    status: (0, mysql_core_1.int)().notNull(),
    userDefined: (0, mysql_core_1.int)("user_defined"),
    userId: (0, mysql_core_1.int)("user_id"),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybLogs = (0, mysql_core_1.mysqlTable)("cyb_logs", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id").notNull(),
    type: (0, mysql_core_1.varchar)({ length: 50 }),
    callMethod: (0, mysql_core_1.varchar)("call_method", { length: 100 }),
    logMessage: (0, mysql_core_1.text)("log_message"),
    payload: (0, mysql_core_1.text)(),
    statusCode: (0, mysql_core_1.int)("status_code"),
    custumMessage: (0, mysql_core_1.text)("custum_message").notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }).notNull(),
});
exports.cybManualDocumentVerify = (0, mysql_core_1.mysqlTable)("cyb_manual_document_verify", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id").notNull(),
    doctype: (0, mysql_core_1.int)(),
    description: (0, mysql_core_1.text)(),
    docs: (0, mysql_core_1.text)(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 50 }),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
}, (table) => [
    (0, mysql_core_1.index)("user_index").on(table.userId),
]);
exports.cybMenu = (0, mysql_core_1.mysqlTable)("cyb_menu", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    parentId: (0, mysql_core_1.int)("parent_id"),
    name: (0, mysql_core_1.varchar)({ length: 250 }),
    fafa: (0, mysql_core_1.varchar)({ length: 250 }),
    link: (0, mysql_core_1.varchar)({ length: 250 }),
    sortOrder: (0, mysql_core_1.int)("sort_order"),
    status: (0, mysql_core_1.int)(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybMergeCompany = (0, mysql_core_1.mysqlTable)("cyb_merge_company", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    mergeCompany: (0, mysql_core_1.int)("merge_company"),
    mainCompany: (0, mysql_core_1.int)("main_company"),
    status: (0, mysql_core_1.tinyint)().default(1),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted"),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }).notNull(),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }).notNull(),
});
exports.cybMergeCompanyRequest = (0, mysql_core_1.mysqlTable)("cyb_merge_company_request", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    requestFrom: (0, mysql_core_1.int)("request_from").notNull(),
    requestTo: (0, mysql_core_1.int)("request_to").notNull(),
    status: (0, mysql_core_1.tinyint)(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybMessage = (0, mysql_core_1.mysqlTable)("cyb_message", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    sender: (0, mysql_core_1.int)().notNull(),
    receiver: (0, mysql_core_1.int)().notNull(),
    forApproval: (0, mysql_core_1.int)("for_approval").default(1).notNull(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybMessageHistory = (0, mysql_core_1.mysqlTable)("cyb_message_history", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    messageId: (0, mysql_core_1.int)("message_id").default(0),
    sender: (0, mysql_core_1.int)().notNull(),
    receiver: (0, mysql_core_1.int)().notNull(),
    message: (0, mysql_core_1.text)(),
    doc: (0, mysql_core_1.text)(),
    isViewed: (0, mysql_core_1.int)("is_viewed").default(0).notNull(),
    forApproval: (0, mysql_core_1.int)("for_approval").default(1).notNull(),
    viewDatetime: (0, mysql_core_1.varchar)("view_datetime", { length: 250 }),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybMigrations = (0, mysql_core_1.mysqlTable)("cyb_migrations", {
    id: (0, mysql_core_1.bigint)({ mode: "number" }).autoincrement().primaryKey().notNull(),
    version: (0, mysql_core_1.varchar)({ length: 255 }).notNull(),
    class: (0, mysql_core_1.varchar)({ length: 255 }).notNull(),
    group: (0, mysql_core_1.varchar)({ length: 255 }).notNull(),
    namespace: (0, mysql_core_1.varchar)({ length: 255 }).notNull(),
    time: (0, mysql_core_1.int)().notNull(),
    batch: (0, mysql_core_1.int)().notNull(),
});
exports.cybMonth = (0, mysql_core_1.mysqlTable)("cyb_month", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.text)(),
    monthNumber: (0, mysql_core_1.int)("month_number"),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybNoticePeriod = (0, mysql_core_1.mysqlTable)("cyb_notice_period", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    status: (0, mysql_core_1.int)(),
    type: (0, mysql_core_1.char)({ length: 10 }),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybNotifications = (0, mysql_core_1.mysqlTable)("cyb_notifications", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    sender: (0, mysql_core_1.int)().notNull(),
    receiver: (0, mysql_core_1.int)().notNull(),
    message: (0, mysql_core_1.text)(),
    doc: (0, mysql_core_1.text)(),
    type: (0, mysql_core_1.varchar)({ length: 20 }),
    link: (0, mysql_core_1.text)(),
    redirect: (0, mysql_core_1.varchar)({ length: 50 }),
    isViewed: (0, mysql_core_1.int)("is_viewed").default(0).notNull(),
    slug: (0, mysql_core_1.varchar)({ length: 50 }),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybOtp = (0, mysql_core_1.mysqlTable)("cyb_otp", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    phone: (0, mysql_core_1.varchar)({ length: 20 }).notNull(),
    email: (0, mysql_core_1.varchar)({ length: 250 }),
    otp: (0, mysql_core_1.varchar)({ length: 10 }).notNull(),
    type: (0, mysql_core_1.mysqlEnum)(['LOGIN', 'SIGNUP', 'VERIFICATION']),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0),
    expiry: (0, mysql_core_1.varchar)({ length: 11 }).notNull(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 100 }),
}, (table) => [
    (0, mysql_core_1.index)("otp_index").on(table.phone, table.email, table.otp, table.isDeleted),
]);
exports.cybPermission = (0, mysql_core_1.mysqlTable)("cyb_permission", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    permissionName: (0, mysql_core_1.text)("permission_name").notNull(),
    permissionKey: (0, mysql_core_1.text)("permission_key"),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
});
exports.cybPortfolioDocumentType = (0, mysql_core_1.mysqlTable)("cyb_portfolio_document_type", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    type: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybRamdomWidgets = (0, mysql_core_1.mysqlTable)("cyb_ramdom_widgets", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    heading: (0, mysql_core_1.text)().notNull(),
    status: (0, mysql_core_1.int)(),
    variant: (0, mysql_core_1.varchar)({ length: 250 }),
    widget: (0, mysql_core_1.varchar)({ length: 20 }),
    type: (0, mysql_core_1.varchar)({ length: 50 }),
    api: (0, mysql_core_1.varchar)({ length: 50 }),
    minLimit: (0, mysql_core_1.int)("min_limit"),
    slug: (0, mysql_core_1.varchar)({ length: 250 }),
    apiSlug: (0, mysql_core_1.varchar)("api_slug", { length: 250 }),
});
exports.cybRatingWeight = (0, mysql_core_1.mysqlTable)("cyb_rating_weight", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    session: (0, mysql_core_1.varchar)({ length: 100 }),
    weight: (0, mysql_core_1.varchar)({ length: 20 }),
    type: (0, mysql_core_1.mysqlEnum)(['latest', 'previous', 'others', 'session_avg', 'progressive', 'criteria_lifetime', 'unique_criteria']),
    weightType: (0, mysql_core_1.tinyint)("weight_type"),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybReels = (0, mysql_core_1.mysqlTable)("cyb_reels", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    title: (0, mysql_core_1.text)(),
    thumbnailImage: (0, mysql_core_1.text)("thumbnail_image"),
    video: (0, mysql_core_1.varchar)({ length: 255 }),
    videoLink: (0, mysql_core_1.varchar)("video_link", { length: 255 }),
    slug: (0, mysql_core_1.text)(),
    sortOrder: (0, mysql_core_1.int)("sort_order"),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybReportReviews = (0, mysql_core_1.mysqlTable)("cyb_report_reviews", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id").notNull(),
    reviewId: (0, mysql_core_1.int)("review_id").notNull(),
    message: (0, mysql_core_1.text)(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    status: (0, mysql_core_1.int)().default(1),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
});
exports.cybRestaurants = (0, mysql_core_1.mysqlTable)("cyb_restaurants", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 255 }).notNull(),
    email: (0, mysql_core_1.varchar)({ length: 255 }),
    phone: (0, mysql_core_1.varchar)({ length: 20 }),
    password: (0, mysql_core_1.varchar)({ length: 255 }),
    token: (0, mysql_core_1.text)(),
    profile: (0, mysql_core_1.text)(),
    address: (0, mysql_core_1.text)(),
    googleMap: (0, mysql_core_1.text)("google_map"),
    discount: (0, mysql_core_1.varchar)({ length: 50 }),
    banner: (0, mysql_core_1.text)(),
    shortDescription: (0, mysql_core_1.text)(),
    category: (0, mysql_core_1.int)(),
    status: (0, mysql_core_1.tinyint)().default(1),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0),
    createDate: (0, mysql_core_1.timestamp)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.timestamp)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("restaurant_index").on(table.phone, table.isDeleted, table.status),
    (0, mysql_core_1.unique)("email").on(table.email),
]);
exports.cybRestaurantCategory = (0, mysql_core_1.mysqlTable)("cyb_restaurant_category", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.timestamp)("create_date", { mode: 'string' }).notNull(),
    modifyDate: (0, mysql_core_1.timestamp)("modify_date", { mode: 'string' }).notNull(),
});
exports.cybRestaurantCustomers = (0, mysql_core_1.mysqlTable)("cyb_restaurant_customers", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    restaurantId: (0, mysql_core_1.int)("restaurant_id"),
    customerId: (0, mysql_core_1.varchar)("customer_id", { length: 150 }),
    // you can use { mode: 'date' }, if you want to have Date as type for this column
    firstVisitDate: (0, mysql_core_1.date)("first_visit_date", { mode: 'string' }),
    // you can use { mode: 'date' }, if you want to have Date as type for this column
    lastVisitDate: (0, mysql_core_1.date)("last_visit_date", { mode: 'string' }),
    totalVisits: (0, mysql_core_1.int)("total_visits"),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }).notNull(),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }).notNull(),
});
exports.cybResumeDownload = (0, mysql_core_1.mysqlTable)("cyb_resume_download", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id"),
    templeteId: (0, mysql_core_1.int)("templete_id"),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }).notNull(),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }).notNull(),
});
exports.cybResumeTemplates = (0, mysql_core_1.mysqlTable)("cyb_resume_templates", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    thumbnail: (0, mysql_core_1.varchar)({ length: 100 }),
    status: (0, mysql_core_1.int)(),
    short: (0, mysql_core_1.int)(),
    type: (0, mysql_core_1.tinyint)().notNull(),
    templatePath: (0, mysql_core_1.varchar)("template_path", { length: 250 }),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybRoleTypes = (0, mysql_core_1.mysqlTable)("cyb_role_types", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    status: (0, mysql_core_1.int)(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybSalary = (0, mysql_core_1.mysqlTable)("cyb_salary", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    status: (0, mysql_core_1.int)(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybSchedulars = (0, mysql_core_1.mysqlTable)("cyb_schedulars", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }),
    emails: (0, mysql_core_1.longtext)(),
    inactiveEmails: (0, mysql_core_1.longtext)("inactive_emails"),
    template: (0, mysql_core_1.int)(),
    trigger: (0, mysql_core_1.datetime)({ mode: 'string' }),
    delivered: (0, mysql_core_1.longtext)(),
    notDelivered: (0, mysql_core_1.longtext)("not_delivered"),
    notSend: (0, mysql_core_1.longtext)("not_send"),
    status: (0, mysql_core_1.int)().default(0).notNull(),
    execute: (0, mysql_core_1.tinyint)().default(0).notNull(),
    type: (0, mysql_core_1.varchar)({ length: 150 }),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
    sentTime: (0, mysql_core_1.datetime)("sent_time", { mode: 'string' }),
});
exports.cybSchedularEmailTemp = (0, mysql_core_1.mysqlTable)("cyb_schedular_email_temp", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    schedularId: (0, mysql_core_1.int)("schedular_id"),
    email: (0, mysql_core_1.varchar)({ length: 250 }),
    status: (0, mysql_core_1.int)().default(0).notNull(),
    deliver: (0, mysql_core_1.int)().default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybSchedularHistory = (0, mysql_core_1.mysqlTable)("cyb_schedular_history", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    schedularId: (0, mysql_core_1.int)("schedular_id"),
    email: (0, mysql_core_1.varchar)({ length: 250 }),
    template: (0, mysql_core_1.int)(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("idx_email_template").on(table.email, table.template),
]);
exports.cybSetting = (0, mysql_core_1.mysqlTable)("cyb_setting", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    code: (0, mysql_core_1.varchar)({ length: 50 }),
    key: (0, mysql_core_1.varchar)({ length: 50 }),
    value: (0, mysql_core_1.varchar)({ length: 250 }),
    name: (0, mysql_core_1.text)(),
    detail: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
});
exports.cybSkill = (0, mysql_core_1.mysqlTable)("cyb_skill", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    userId: (0, mysql_core_1.int)("user_id"),
    userDefined: (0, mysql_core_1.int)("user_defined"),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("skill_index").on(table.status),
]);
exports.cybSkillRating = (0, mysql_core_1.mysqlTable)("cyb_skill_rating", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id").notNull(),
    reviewId: (0, mysql_core_1.int)("review_id"),
    experienceId: (0, mysql_core_1.int)("experience_id"),
    skillId: (0, mysql_core_1.int)("skill_id").notNull(),
    rating: (0, mysql_core_1.int)().default(0).notNull(),
    showHome: (0, mysql_core_1.tinyint)("show_home").default(0).notNull(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("skill_rating_index").on(table.reviewId, table.showHome, table.skillId, table.userId, table.isDeleted),
]);
exports.cybSkillRatingHistory = (0, mysql_core_1.mysqlTable)("cyb_skill_rating_history", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    reviewHistoryId: (0, mysql_core_1.int)("review_history_id"),
    skillId: (0, mysql_core_1.int)("skill_id").notNull(),
    rating: (0, mysql_core_1.int)().default(0).notNull(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("skill_rating_index").on(table.skillId),
]);
exports.cybState = (0, mysql_core_1.mysqlTable)("cyb_state", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 56 }),
    country: (0, mysql_core_1.int)(),
    code: (0, mysql_core_1.varchar)({ length: 5 }),
    status: (0, mysql_core_1.int)(),
    slug: (0, mysql_core_1.text)(),
}, (table) => [
    (0, mysql_core_1.index)("state_index").on(table.id, table.country, table.status),
]);
exports.cybSuggestion = (0, mysql_core_1.mysqlTable)("cyb_suggestion", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 500 }),
    phone: (0, mysql_core_1.bigint)({ mode: "number" }),
    description: (0, mysql_core_1.text)(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybTag = (0, mysql_core_1.mysqlTable)("cyb_tag", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 150 }),
    status: (0, mysql_core_1.tinyint)().default(1),
    userDefined: (0, mysql_core_1.int)("user_defined"),
    userId: (0, mysql_core_1.int)("user_id"),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybTrackEmails = (0, mysql_core_1.mysqlTable)("cyb_track_emails", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id").notNull(),
    templateId: (0, mysql_core_1.int)("template_id").notNull(),
    schedularId: (0, mysql_core_1.int)("schedular_id"),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
});
exports.cybTriggerEmail = (0, mysql_core_1.mysqlTable)("cyb_trigger_email", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    user: (0, mysql_core_1.int)().notNull(),
    email: (0, mysql_core_1.varchar)({ length: 100 }).notNull(),
    template: (0, mysql_core_1.int)().notNull(),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }).notNull(),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }).notNull(),
});
exports.cybTurnover = (0, mysql_core_1.mysqlTable)("cyb_turnover", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }).notNull(),
    status: (0, mysql_core_1.int)(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybUser = (0, mysql_core_1.mysqlTable)("cyb_user", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey(),
    individualId: (0, mysql_core_1.varchar)("individual_id", { length: 11 }),
    userType: (0, mysql_core_1.int)("user_type").default(1),
    fname: (0, mysql_core_1.varchar)({ length: 60 }),
    lname: (0, mysql_core_1.varchar)({ length: 40 }),
    fullName: (0, mysql_core_1.varchar)("full_name", { length: 255 }).generatedAlwaysAs((0, drizzle_orm_1.sql) `concat_ws(' ',\`fname\`,\`lname\`)`, { mode: "stored" }),
    email: (0, mysql_core_1.varchar)({ length: 80 }),
    phone: (0, mysql_core_1.varchar)({ length: 20 }),
    slug: (0, mysql_core_1.varchar)({ length: 250 }),
    token: (0, mysql_core_1.text)(),
    phoneVerified: (0, mysql_core_1.int)("phone_verified"),
    emailVerified: (0, mysql_core_1.int)("email_verified"),
    gender: (0, mysql_core_1.tinyint)(),
    secondPhoneVerify: (0, mysql_core_1.int)("second_phone_verify"),
    emailAlternateVerify: (0, mysql_core_1.int)("email_alternate_verify"),
    emailAlternate: (0, mysql_core_1.varchar)("email_alternate", { length: 250 }),
    secondPhone: (0, mysql_core_1.varchar)("second_phone", { length: 15 }),
    socialImage: (0, mysql_core_1.text)("social_image"),
    profile: (0, mysql_core_1.text)(),
    password: (0, mysql_core_1.text)(),
    city: (0, mysql_core_1.int)(),
    state: (0, mysql_core_1.int)(),
    accomodation: (0, mysql_core_1.int)(),
    presentAddress: (0, mysql_core_1.text)("present_address"),
    permanentAddress: (0, mysql_core_1.text)("permanent_address"),
    sameAddress: (0, mysql_core_1.tinyint)("same_address"),
    country: (0, mysql_core_1.int)(),
    dob: (0, mysql_core_1.varchar)({ length: 100 }),
    displayType: (0, mysql_core_1.int)("display_type").default(0),
    workStatus: (0, mysql_core_1.int)("work_status"),
    currentPossition: (0, mysql_core_1.int)("current_possition"),
    currentCompany: (0, mysql_core_1.int)("current_company"),
    userDefinedCompany: (0, mysql_core_1.int)("user_defined_company"),
    claimStatus: (0, mysql_core_1.int)("claim_status").default(0),
    profileDescription: (0, mysql_core_1.text)("profile_description"),
    linkdin: (0, mysql_core_1.text)(),
    youtube: (0, mysql_core_1.text)(),
    instagram: (0, mysql_core_1.text)(),
    facebook: (0, mysql_core_1.text)(),
    twitter: (0, mysql_core_1.text)(),
    contactPerson: (0, mysql_core_1.varchar)("contact_person", { length: 250 }),
    website: (0, mysql_core_1.text)(),
    industry: (0, mysql_core_1.int)(),
    incorporateDate: (0, mysql_core_1.varchar)("incorporate_date", { length: 50 }),
    noOfEmployee: (0, mysql_core_1.int)("no_of_employee"),
    turnover: (0, mysql_core_1.int)(),
    companySize: (0, mysql_core_1.int)("company_size"),
    expectedSalary: (0, mysql_core_1.int)("expected_salary"),
    expectedInhand: (0, mysql_core_1.varchar)("expected_inhand", { length: 50 }),
    expectedMode: (0, mysql_core_1.varchar)("expected_mode", { length: 50 }),
    noticePeriod: (0, mysql_core_1.int)("notice_period"),
    onNotice: (0, mysql_core_1.tinyint)("on_notice"),
    onImmediate: (0, mysql_core_1.tinyint)("on_immediate"),
    onExplore: (0, mysql_core_1.tinyint)("on_explore").default(0).notNull(),
    noticeDate: (0, mysql_core_1.varchar)("notice_date", { length: 250 }),
    resume: (0, mysql_core_1.varchar)({ length: 250 }),
    resumeName: (0, mysql_core_1.text)(),
    loginTime: (0, mysql_core_1.datetime)("login_time", { mode: 'string' }),
    registerType: (0, mysql_core_1.varchar)("register_type", { length: 50 }),
    isOnline: (0, mysql_core_1.int)("is_online"),
    referralCode: (0, mysql_core_1.varchar)("referral_code", { length: 50 }),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    appleId: (0, mysql_core_1.varchar)("apple_id", { length: 50 }),
    acceptTerm: (0, mysql_core_1.tinyint)("accept_term").default(1).notNull(),
    createdBy: (0, mysql_core_1.int)("created_by"),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    userRegisterType: (0, mysql_core_1.tinyint)("user_register_type"),
    methodType: (0, mysql_core_1.varchar)("method_type", { length: 20 }),
    percentage: (0, mysql_core_1.int)(),
    percentageStatus: (0, mysql_core_1.int)("percentage_status").default(0).notNull(),
    cvPop: (0, mysql_core_1.int)(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
    randomValue: (0, mysql_core_1.float)("random_value"),
}, (table) => [
    (0, mysql_core_1.index)("user_index").on(table.state, table.city, table.currentCompany, table.currentPossition, table.country, table.incorporateDate, table.industry, table.fname),
    (0, mysql_core_1.index)("user_index_new").on(table.id, table.userType, table.status, table.onNotice, table.onImmediate, table.onExplore, table.isDeleted, table.percentage),
    (0, mysql_core_1.index)("idx_slug_status_deleted").on(table.slug, table.status, table.isDeleted),
    (0, mysql_core_1.index)("idx_usertype_status_deleted").on(table.userType, table.status, table.isDeleted),
    (0, mysql_core_1.index)("idx_company_filter").on(table.userType, table.claimStatus, table.status, table.isDeleted),
    (0, mysql_core_1.index)("idx_user_deleted").on(table.id, table.isDeleted),
]);
exports.cybUserCertificate = (0, mysql_core_1.mysqlTable)("cyb_user_certificate", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    user: (0, mysql_core_1.int)(),
    university: (0, mysql_core_1.text)(),
    course: (0, mysql_core_1.text)(),
    startDate: (0, mysql_core_1.varchar)("start_date", { length: 250 }),
    endDate: (0, mysql_core_1.varchar)("end_date", { length: 250 }),
    ongoing: (0, mysql_core_1.tinyint)(),
    certificate: (0, mysql_core_1.text)(),
    certificateId: (0, mysql_core_1.varchar)("certificate_id", { length: 50 }),
    url: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    createdBy: (0, mysql_core_1.int)("created_by"),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybUserContacts = (0, mysql_core_1.mysqlTable)("cyb_user_contacts", {
    id: (0, mysql_core_1.bigint)({ mode: "number" }).autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.bigint)("user_id", { mode: "number" }).notNull(),
    mobile: (0, mysql_core_1.varchar)({ length: 20 }).notNull(),
    contactName: (0, mysql_core_1.varchar)("contact_name", { length: 255 }),
    contactHash: (0, mysql_core_1.varchar)("contact_hash", { length: 64 }),
    lastSyncedAt: (0, mysql_core_1.datetime)("last_synced_at", { mode: 'string' }),
    createdAt: (0, mysql_core_1.datetime)("created_at", { mode: 'string' }),
    updatedAt: (0, mysql_core_1.datetime)("updated_at", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.unique)("unique_user_mobile").on(table.userId, table.mobile),
]);
exports.cybUserDetails = (0, mysql_core_1.mysqlTable)("cyb_user_details", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id").notNull(),
    noticeEmployments: (0, mysql_core_1.text)("notice_employments"),
    latitude: (0, mysql_core_1.varchar)({ length: 50 }),
    longitude: (0, mysql_core_1.varchar)({ length: 50 }),
    landline: (0, mysql_core_1.varchar)({ length: 20 }),
    exploringOption: (0, mysql_core_1.text)("exploring_option"),
    exploringDetails: (0, mysql_core_1.text)("exploring_details"),
    domain: (0, mysql_core_1.varchar)({ length: 255 }),
    isVerified: (0, mysql_core_1.tinyint)("is_verified").default(0),
    verifiedAt: (0, mysql_core_1.timestamp)("verified_at", { mode: 'string' }),
    domainCreatedAt: (0, mysql_core_1.timestamp)("domain_created_at", { mode: 'string' }),
    import: (0, mysql_core_1.tinyint)().default(0).notNull(),
}, (table) => [
    (0, mysql_core_1.index)("user_id").on(table.userId),
]);
exports.cybUserDeviceTokens = (0, mysql_core_1.mysqlTable)("cyb_user_device_tokens", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id"),
    deviceType: (0, mysql_core_1.varchar)("device_type", { length: 20 }),
    deviceId: (0, mysql_core_1.varchar)("device_id", { length: 50 }),
    deviceToken: (0, mysql_core_1.text)("device_token"),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }).notNull(),
    status: (0, mysql_core_1.int)().default(1),
    createdAt: (0, mysql_core_1.datetime)("created_at", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.unique)("user_id").on(table.userId, table.deviceId),
]);
exports.cybUserDocument = (0, mysql_core_1.mysqlTable)("cyb_user_document", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    user: (0, mysql_core_1.int)(),
    doctype: (0, mysql_core_1.int)(),
    doc: (0, mysql_core_1.text)(),
    docnumber: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(0).notNull(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybUserDomains = (0, mysql_core_1.mysqlTable)("cyb_user_domains", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id").notNull(),
    addedBy: (0, mysql_core_1.int)("added_by"),
    domain: (0, mysql_core_1.varchar)({ length: 255 }),
    isEmailBased: (0, mysql_core_1.tinyint)("is_email_based").default(0),
    email: (0, mysql_core_1.varchar)({ length: 50 }),
    verificationKey: (0, mysql_core_1.text)("verification_key"),
    isVerified: (0, mysql_core_1.tinyint)("is_verified").default(0),
    verifiedAt: (0, mysql_core_1.timestamp)("verified_at", { mode: 'string' }),
    domainCreatedAt: (0, mysql_core_1.datetime)("domain_created_at", { mode: 'string' }),
    domainModifyAt: (0, mysql_core_1.datetime)("domain_modify_at", { mode: 'string' }).notNull(),
    verificationAttempts: (0, mysql_core_1.int)("verification_attempts").default(0),
    lastVerificationAttempt: (0, mysql_core_1.timestamp)("last_verification_attempt", { mode: 'string' }),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
}, (table) => [
    (0, mysql_core_1.index)("user_id").on(table.userId),
]);
exports.cybUserEducation = (0, mysql_core_1.mysqlTable)("cyb_user_education", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    user: (0, mysql_core_1.int)(),
    university: (0, mysql_core_1.int)(),
    course: (0, mysql_core_1.int)(),
    courseType: (0, mysql_core_1.int)("course_type"),
    state: (0, mysql_core_1.int)(),
    city: (0, mysql_core_1.int)(),
    notApplicable: (0, mysql_core_1.int)("not_applicable").default(0).notNull(),
    // you can use { mode: 'date' }, if you want to have Date as type for this column
    startingDate: (0, mysql_core_1.date)("starting_date", { mode: 'string' }),
    // you can use { mode: 'date' }, if you want to have Date as type for this column
    endingDate: (0, mysql_core_1.date)("ending_date", { mode: 'string' }),
    ongoing: (0, mysql_core_1.tinyint)(),
    country: (0, mysql_core_1.int)(),
    ishighest: (0, mysql_core_1.tinyint)(),
    certificate: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createdBy: (0, mysql_core_1.int)("created_by"),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("education_index").on(table.user, table.university, table.course, table.courseType, table.state, table.city, table.country, table.ishighest, table.isDeleted, table.status),
]);
exports.cybUserExperience = (0, mysql_core_1.mysqlTable)("cyb_user_experience", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    user: (0, mysql_core_1.int)(),
    company: (0, mysql_core_1.int)(),
    employmentType: (0, mysql_core_1.int)("employment_type"),
    designation: (0, mysql_core_1.int)(),
    workEmail: (0, mysql_core_1.varchar)("work_email", { length: 100 }),
    workEmailDate: (0, mysql_core_1.datetime)("work_email_date", { mode: 'string' }),
    salary: (0, mysql_core_1.varchar)({ length: 50 }),
    salaryInhand: (0, mysql_core_1.varchar)("salary_inhand", { length: 250 }),
    salaryMode: (0, mysql_core_1.varchar)("salary_mode", { length: 20 }),
    // you can use { mode: 'date' }, if you want to have Date as type for this column
    joiningDate: (0, mysql_core_1.date)("joining_date", { mode: 'string' }),
    workedTillDate: (0, mysql_core_1.varchar)("worked_till_date", { length: 250 }),
    department: (0, mysql_core_1.int)(),
    stillWorking: (0, mysql_core_1.int)("still_working").default(0).notNull(),
    skill: (0, mysql_core_1.text)(),
    description: (0, mysql_core_1.text)(),
    approved: (0, mysql_core_1.int)().default(0).notNull(),
    lastReview: (0, mysql_core_1.int)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    hired: (0, mysql_core_1.tinyint)(),
    state: (0, mysql_core_1.int)(),
    city: (0, mysql_core_1.int)(),
    addedBy: (0, mysql_core_1.int)("added_by").default(0).notNull(),
    createdBy: (0, mysql_core_1.int)("created_by"),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 100 }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
    expiry: (0, mysql_core_1.datetime)({ mode: 'string' }),
    certificate: (0, mysql_core_1.text)(),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
}, (table) => [
    (0, mysql_core_1.index)("multi index").on(table.user, table.company, table.designation, table.department),
    (0, mysql_core_1.index)("idx_uex_company_filter").on(table.company, table.isDeleted, table.status, table.approved, table.user, table.employmentType, table.designation, table.department, table.hired, table.stillWorking),
]);
exports.cybUserExperienceRating = (0, mysql_core_1.mysqlTable)("cyb_user_experience_rating", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    experience: (0, mysql_core_1.int)(),
    company: (0, mysql_core_1.int)(),
    rating: (0, mysql_core_1.int)().default(0).notNull(),
    review: (0, mysql_core_1.text)(),
    doc: (0, mysql_core_1.text)(),
    link: (0, mysql_core_1.text)(),
    addedBy: (0, mysql_core_1.int)("added_by").default(0).notNull(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    approved: (0, mysql_core_1.int)().default(0),
    expiry: (0, mysql_core_1.varchar)({ length: 250 }),
    showReview: (0, mysql_core_1.tinyint)("show_review"),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    showHome: (0, mysql_core_1.tinyint)("show_home").default(0),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("indx_user_experience_rating").on(table.experience, table.company, table.approved, table.status, table.showHome),
]);
exports.cybUserExperienceRatingHistory = (0, mysql_core_1.mysqlTable)("cyb_user_experience_rating_history", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    ratingId: (0, mysql_core_1.int)("rating_id"),
    rating: (0, mysql_core_1.int)().default(0),
    review: (0, mysql_core_1.text)(),
    doc: (0, mysql_core_1.text)(),
    link: (0, mysql_core_1.text)(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybUserGroup = (0, mysql_core_1.mysqlTable)("cyb_user_group", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    groupId: (0, mysql_core_1.int)("group_id"),
    menuPermission: (0, mysql_core_1.text)("menu_permission"),
    eventPermission: (0, mysql_core_1.text)("event_permission"),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    addedBy: (0, mysql_core_1.int)("added_by"),
    ownerId: (0, mysql_core_1.int)("owner_id"),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybUserLanguage = (0, mysql_core_1.mysqlTable)("cyb_user_language", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    user: (0, mysql_core_1.int)(),
    language: (0, mysql_core_1.int)(),
    verbal: (0, mysql_core_1.int)(),
    written: (0, mysql_core_1.int)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("langauge_index").on(table.user, table.status, table.isDeleted, table.language, table.verbal, table.written),
]);
exports.cybUserLevels = (0, mysql_core_1.mysqlTable)("cyb_user_levels", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    user: (0, mysql_core_1.int)().notNull(),
    level: (0, mysql_core_1.int)(),
    createdAt: (0, mysql_core_1.datetime)("created_at", { mode: 'string' }).notNull(),
    updatedAt: (0, mysql_core_1.datetime)("updated_at", { mode: 'string' }).notNull(),
});
exports.cybUserLoginHistory = (0, mysql_core_1.mysqlTable)("cyb_user_login_history", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id").notNull(),
    deviceId: (0, mysql_core_1.varchar)("device_id", { length: 255 }),
    ipAddress: (0, mysql_core_1.varchar)("ip_address", { length: 50 }),
    userAgent: (0, mysql_core_1.text)("user_agent"),
    platform: (0, mysql_core_1.varchar)({ length: 50 }),
    status: (0, mysql_core_1.tinyint)().default(1),
    loginAt: (0, mysql_core_1.datetime)("login_at", { mode: 'string' }),
    logoutAt: (0, mysql_core_1.datetime)("logout_at", { mode: 'string' }),
});
exports.cybUserMainGroup = (0, mysql_core_1.mysqlTable)("cyb_user_main_group", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 250 }),
    description: (0, mysql_core_1.varchar)({ length: 255 }),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0),
    companyId: (0, mysql_core_1.int)("company_id"),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybUserPermission = (0, mysql_core_1.mysqlTable)("cyb_user_permission", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id"),
    groupId: (0, mysql_core_1.int)("group_id"),
    addedBy: (0, mysql_core_1.int)("added_by"),
    parentId: (0, mysql_core_1.int)("parent_id").default(0).notNull(),
    status: (0, mysql_core_1.tinyint)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybUserProfileViewRequest = (0, mysql_core_1.mysqlTable)("cyb_user_profile_view_request", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userid: (0, mysql_core_1.int)().notNull(),
    companyid: (0, mysql_core_1.int)().notNull(),
    otp: (0, mysql_core_1.varchar)({ length: 10 }),
    status: (0, mysql_core_1.int)().default(0).notNull(),
    review: (0, mysql_core_1.int)(),
    salary: (0, mysql_core_1.int)(),
    access: (0, mysql_core_1.text)(),
    expiry: (0, mysql_core_1.varchar)({ length: 250 }),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybUserProtfolio = (0, mysql_core_1.mysqlTable)("cyb_user_protfolio", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    user: (0, mysql_core_1.int)(),
    type: (0, mysql_core_1.int)(),
    title: (0, mysql_core_1.text)(),
    description: (0, mysql_core_1.text)(),
    youtube: (0, mysql_core_1.varchar)({ length: 250 }),
    image: (0, mysql_core_1.text)(),
    video: (0, mysql_core_1.text)(),
    pdf: (0, mysql_core_1.text)(),
    url: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    sortOrder: (0, mysql_core_1.int)().default(1),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybUserRelation = (0, mysql_core_1.mysqlTable)("cyb_user_relation", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id"),
    companyId: (0, mysql_core_1.int)("company_id"),
    type: (0, mysql_core_1.tinyint)(),
    permission: (0, mysql_core_1.text)(),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    status: (0, mysql_core_1.int)().default(0).notNull(),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }).notNull(),
});
exports.cybUserSkill = (0, mysql_core_1.mysqlTable)("cyb_user_skill", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    user: (0, mysql_core_1.int)(),
    skill: (0, mysql_core_1.int)(),
    rating: (0, mysql_core_1.int)().default(0),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("skill_index").on(table.status, table.rating, table.user, table.skill, table.isDeleted),
]);
exports.cybUserUpdateExperience = (0, mysql_core_1.mysqlTable)("cyb_user_update_experience", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    experienceId: (0, mysql_core_1.int)("experience_id").notNull(),
    user: (0, mysql_core_1.int)().notNull(),
    salary: (0, mysql_core_1.varchar)({ length: 250 }),
    salaryInhand: (0, mysql_core_1.varchar)("salary_inhand", { length: 50 }),
    salaryMode: (0, mysql_core_1.varchar)("salary_mode", { length: 50 }),
    designation: (0, mysql_core_1.int)(),
    workedTillDate: (0, mysql_core_1.varchar)("worked_till_date", { length: 250 }),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    type: (0, mysql_core_1.int)().notNull(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybUserUpdateExperienceHistory = (0, mysql_core_1.mysqlTable)("cyb_user_update_experience_history", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    updateId: (0, mysql_core_1.int)("update_id"),
    parent: (0, mysql_core_1.int)().default(0),
    experienceId: (0, mysql_core_1.int)("experience_id").notNull(),
    user: (0, mysql_core_1.int)().notNull(),
    salary: (0, mysql_core_1.varchar)({ length: 250 }),
    salaryInhand: (0, mysql_core_1.varchar)("salary_inhand", { length: 50 }),
    salaryMode: (0, mysql_core_1.varchar)("salary_mode", { length: 50 }),
    designation: (0, mysql_core_1.int)(),
    workedTillDate: (0, mysql_core_1.varchar)("worked_till_date", { length: 250 }),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    type: (0, mysql_core_1.int)().notNull(),
    isDeleted: (0, mysql_core_1.int)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybVerifyDocument = (0, mysql_core_1.mysqlTable)("cyb_verify_document", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    userId: (0, mysql_core_1.int)("user_id"),
    doctype: (0, mysql_core_1.varchar)({ length: 20 }),
    docName: (0, mysql_core_1.text)("doc_name"),
    docnumber: (0, mysql_core_1.text)(),
    methodType: (0, mysql_core_1.varchar)("method_type", { length: 20 }),
    verify: (0, mysql_core_1.int)().default(0),
    clientId: (0, mysql_core_1.text)("client_id"),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
}, (table) => [
    (0, mysql_core_1.index)("document_verify").on(table.verify, table.methodType, table.userId),
]);
exports.cybViewImpressions = (0, mysql_core_1.mysqlTable)("cyb_view_impressions", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    currentUser: (0, mysql_core_1.int)("current_user").notNull(),
    remoteId: (0, mysql_core_1.int)("remote_id").notNull(),
    type: (0, mysql_core_1.mysqlEnum)(['Profile', 'Job']),
    isDeleted: (0, mysql_core_1.tinyint)("is_deleted").default(0).notNull(),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
exports.cybWebMenu = (0, mysql_core_1.mysqlTable)("cyb_web_menu", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    parentId: (0, mysql_core_1.int)("parent_id"),
    type: (0, mysql_core_1.int)(),
    name: (0, mysql_core_1.varchar)({ length: 250 }),
    icon: (0, mysql_core_1.text)(),
    link: (0, mysql_core_1.varchar)({ length: 250 }),
    sortOrder: (0, mysql_core_1.int)("sort_order"),
    status: (0, mysql_core_1.int)(),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 250 }),
    modifyDate: (0, mysql_core_1.varchar)("modify_date", { length: 250 }),
});
exports.cybWidgets = (0, mysql_core_1.mysqlTable)("cyb_widgets", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.varchar)({ length: 255 }).notNull(),
    status: (0, mysql_core_1.int)().default(1),
    createDate: (0, mysql_core_1.varchar)("create_date", { length: 20 }),
});
exports.cybWidgetPosition = (0, mysql_core_1.mysqlTable)("cyb_widget_position", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    widgetId: (0, mysql_core_1.int)("widget_id").notNull(),
    placement: (0, mysql_core_1.int)(),
    variant: (0, mysql_core_1.varchar)({ length: 50 }),
    limitRecord: (0, mysql_core_1.int)("limit_record"),
});
exports.cybWorkType = (0, mysql_core_1.mysqlTable)("cyb_work_type", {
    id: (0, mysql_core_1.int)().autoincrement().primaryKey().notNull(),
    name: (0, mysql_core_1.text)(),
    status: (0, mysql_core_1.int)().default(1).notNull(),
    userDefined: (0, mysql_core_1.int)("user_defined"),
    userId: (0, mysql_core_1.int)("user_id"),
    createDate: (0, mysql_core_1.datetime)("create_date", { mode: 'string' }),
    modifyDate: (0, mysql_core_1.datetime)("modify_date", { mode: 'string' }),
});
