import { otpSend, maskMobile } from "../../utils/msg91";
import type { HandlerResult } from "../types";

/**
 * SQS payload for MSG91 SMS OTP delivery.
 * Mirrors PHP otpSend($mobile, $otp) used by login send_otp_new.
 *
 * Login OTP uses direct MSG91 by default; this handler is for optional
 * SEND_SMS jobs (MSG91_USE_SQS=1) or other producers.
 */
export interface SmsPayload {
	/** Digits only preferred; `+` is stripped. Include country code (e.g. 91…). */
	phone: string;
	/** App-generated 6-digit OTP (not generated by MSG91). */
	otp: string | number;
	/** Optional free-form body for non-OTP SMS (not used by MSG91 OTP API). */
	message?: string;
}

export async function handleSms(data: SmsPayload): Promise<HandlerResult> {
	try {
		const masked = data.phone ? maskMobile(String(data.phone)) : "(none)";
		console.log("[SMS] Sending SMS OTP via MSG91 to", masked);

		if (!data.phone) {
			console.warn("[SMS] No phone number provided");
			return { success: false, message: "No phone number" };
		}

		if (data.otp === undefined || data.otp === null || data.otp === "") {
			console.warn("[SMS] No OTP provided for", masked);
			return { success: false, message: "No OTP" };
		}

		const result = await otpSend(data.phone, data.otp);

		if (result) {
			console.log("[SMS] OTP sent OK to", masked);
			return { success: true, message: "SMS OTP sent" };
		}

		console.error("[SMS] OTP send failed for", masked);
		throw new Error(`SMS OTP FAILED for: ${masked}`);
	} catch (error) {
		console.error("[SMS] Error:", error);
		throw error;
	}
}
